- name: Aktualisiere Git-Repository auf entferntem Host
  hosts: "{{ target_server }}"
  gather_facts: no
  remote_user: "{{ target_user }}"
  collections:
    - lvrfrc87.git_acp

  tasks:
    - name: Das Repository Pushen.
      become: true
      become_user: "{{ git_local_user }}"
      git_acp:
        path: "{{ local_dir }}"
        branch: "{{ git_branch }}"
        comment: "Automatic Changes by iobroker (interface)"
        add: [ "." ]
        url: "{{ full_bare_repo }}"
        push_force: true