- name: Ping Machines Test
  hosts: all
  remote_user: "{{ target_user }}"
  gather_facts: true

  tasks:
   - name: Ping my hosts
     ping:
   - name: Print all available facts
     ansible.builtin.debug:
     #var: ansible_facts
       msg: "{{ ansible_facts | dict2items | selectattr('value.macaddress', 'defined') | map(attribute='value') | list }}"
