#!/bin/sh
# Read the Readme for Needed Tools!
export DEPLOYCODE_SILENT_ANSIBLE=1
export DEPLOYCODE_SILENT_INOTIFY=0

# Get Libraries.
# shellcheck source=usr/lib/libDeploy
# Priorize, the Internal Libraries - that's the default.
if [ -f "/usr/lib/libDeploy" ]; then . /usr/lib/libDeploy; else . ./usr/lib/libDeploy; fi
# Priorize, the Development Libs in this folder, that's for Test envirement.
#if [ -r "./usr/lib/libDeploy" ]; then . ./usr/lib/libDeploy; else . /usr/lib/libDeploy; fi

# Search for Playbook Folders..
pb_folder="/etc/deploycode/playbooks/"
[ ! -d "$pb_folder" ] && pb_folder="./etc/deploycode/playbooks"

[ ! -d "$pb_folder" ] && {
	echo "Error! Can not found the Playbook folder. Aborting Script."
	exit 0
}

pb_vars_folder="/etc/deploycode/playbook-vars/"
[ ! -d "$pb_vars_folder" ] && {
	echo "Error! Can not found the Playbook-Vars Folder folder ($pb_vars_folder) folder. Aborting Script."
	exit 0
}

config_folder="/etc/deploycode/configs-enabled"
[ ! -d "$config_folder" ] && {
	echo "Error! Can not found the Config-Enabled folder ($config_folder) folder. Aborting Script."
	exit 0
}

pb_tmp_pids="/tmp/deploycode/pids/"
[ ! -d "$pb_tmp_pids" ] && mkdir -p "$pb_tmp_pids"

ctrl_c() {
	echo "** CTRL-C Pressed. Delete RUnning PIDS..."
	kill_runnings
}

kill_runnings() {
	count_pids=0
	#count_pids=$(ls $pb_tmp_pids/*.pid 2>/dev/null | wc -w)
	count_pids=$(count_folder_files "$pb_tmp_pids" "pid")
	[ ! "$count_pids" = "0" ] || return 0

	for file in "$pb_tmp_pids"/*.pid; do
		pid=$(cat "$file")
		echo "Killing PID: $pid"
		[ -z "$pid" ] && continue

		pkill -TERM -P "$pid"
		[ -f "$file" ] && rm -f "$file"
	done
}

# trap ctrl-c and Termination..
trap ctrl_c INT
trap kill_runnings TERM

cd "$config_folder" || exit 1
count_configs=$(count_folder_files "$config_folder" "conf")
count_run=0
for file in "$config_folder"/*.conf; do

	echo Working on: "$file"
	[ -L "$file" ] && {
		file=$(readlink "$file")
		file=$(realpath "$file")
	}
	count_run=$((count_run + 1))
	echo "Starting run $count_run from $count_configs"

	# Its not The Last Config - Start in the Background.
	[ ! "$count_run" = "$count_configs" ] && {
		watch_for_run_pb "$file" &
		watch_pid="$!"
		[ -n "$watch_pid" ] && echo "$watch_pid" >"${pb_tmp_pids}${watch_pid}.pid"
	}

	# Its the Last Config - Start in the Foreground.
	[ "$count_run" = "$count_configs" ] && watch_for_run_pb "$file"
done
