# Config file for /usr/bin/ocm-deploy.
# IMPORTANT: configure an existing directory to watch.
inotify_watchdir:/srv/git/example.git
playbook1:git-pull
vars_playbook1:example

# More ordered playbooks may be defined with consecutive numbers.
# playbook2:test-ping
# vars_playbook2:example
