# Config file for Deploycode Skript in /usr/bin/deploycode.
# IMPORTANT: The Watchdir,
inotify_watchdir:/git/yvww/ansible_clients_windows.git
playbook1:git-pull
vars_playbook1:ansible_clients_windows

# More Playbooks are Definable over 1,2,3
#playbook2:test1
#vars_playbook2:test2
### End Here